Attempt to address CI failure
```
IE 11.0 (Windows 8.1) ERROR
133
  Expected identifier, string or number
134
  at @stimulus/core/dist/tests/index.js:2281:1
135

136
  SyntaxError: Expected identifier, string or number
137
     at ./packages/@stimulus/polyfills/index.js (@stimulus/core/dist/tests/index.js:2281:1)
```

```
IE 11.0 (Windows 8.1)  target disconnected callback when element is removed FAILED
125
	Promise rejected during "target disconnected callback when element is removed": Object doesn't support property or method 'remove'
126
	TypeError: Object doesn't support property or method 'remove'
127
	   at Anonymous function (eval code:191:25)
```